import { Session } from "inspector";
import "./globals.css";
import SideBar from "@/components/SideBar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="bg-[#202123] overflow-y-auto md:min-w-[260px] ">
            <SideBar />
          </div>
          <div className="bg-[#343541] flex-1 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
